CREATE TYPE whiskey_name AS ENUM (
    'Irish Whiskey',
    'Scotch Whisky',
    'Japanese Whisky',
    'Canadian Whisky',
    'Bourbon Whiskey',
    'Tennessee Whiskey',
    'Rye Whiskey',
    'Blended Whiskey',
    'Single Malt Whisky'
);

CREATE TYPE cocktail_glass AS ENUM (
    'Martini',
    'Highball',
    'Lowball',
    'Snifter'
);

CREATE TABLE recipes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cocktail_name TEXT NOT NULL,
    cocktail_type cocktail_glass NOT NULL,
    whiskey_type whiskey_name NOT NULL,
    description TEXT,
    date_created TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by INTEGER REFERENCES users(id) ON DELETE SET NULL
);